"""empty message

Revision ID: 36079316183f
Revises: 8b7b22e69de8
Create Date: 2026-01-03 15:50:06.978315

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '36079316183f'
down_revision: Union[str, Sequence[str], None] = '8b7b22e69de8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('actor', sa.Column('user_id', sa.Integer(), nullable=False))
    op.add_column('actor', sa.Column('movie_id', sa.Integer(), nullable=False))
    op.drop_constraint(op.f('actor_actor_id_fkey'), 'actor', type_='foreignkey')
    op.create_foreign_key(None, 'actor', 'movie', ['movie_id'], ['id'])
    op.create_foreign_key(None, 'actor', 'custom_user', ['user_id'], ['id'])
    op.drop_column('actor', 'actor_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('actor', sa.Column('actor_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'actor', type_='foreignkey')
    op.drop_constraint(None, 'actor', type_='foreignkey')
    op.create_foreign_key(op.f('actor_actor_id_fkey'), 'actor', 'custom_user', ['actor_id'], ['id'])
    op.drop_column('actor', 'movie_id')
    op.drop_column('actor', 'user_id')
    # ### end Alembic commands ###
